### ISSUE TITLE
Audio Automatically Downloading

### ISSUE THREAD

**Issue by smbsimon** [vprnet/podcast-directory#4]
Hi, JavaScript pros. Hoping you can help!

Vermont Public Radio has been having some serious load time problems with the audio on this [page](http://www.vpr.net/apps/podcasts/). Originally, we had play buttons for each recent episode of each podcast. That looked great and provided a nice service for those looking to quickly discover some new voices. There was one glaring problem, though: All mp3s on the page were automatically downloading every time someone visited the page. That's no good. That's the opposite of good. 

The temporary fix was to just remove the few lines of code from the template that were rendering each podcast's most recent episode on the homepage. This temporary fix happened [here](https://github.com/vprnet/podcast-directory/commit/b2e73d25e45819c323bb1096466d9cd82e8e7978). 

There are a few tricky things at play:
- This repo was built by taking bits and pieces from a few different existing VPR repos, so there's very likely a lot of cruft in here. I'm well aware of that.
- There are no tests, because I am the absolute worst.
- Swapping preload='auto' to preload='none' in the macros template does not seem to change anything. 

I have plenty of hypotheses, and they all circle back to my room-for-improvement JS chops. I think I really just need an event listener on the play buttons, yeah? Something in [here](https://github.com/vprnet/podcast-directory/blob/master/app/static/dev/js/player.js) that can know to download one specific audio file when one specific play button is pressed. Otherwise nothing else needs to happen when the page loads. 

What am I missing?

Thanks in advance,
Sara

**Comment by derekprior** [comment]
Grasping at straws here, but how about `preload="metadata"`? If `none` didn't work, I doubt this would work, but maybe worth a quick shot?

**Comment by smbsimon** [comment]
@derekprior Tried that, too. Alas. Thanks, though!

**Comment by summer4096** [comment]
Slack is back up, but you can solve this by only bringing in the audio tag when the user hits the play button. You can also leave the `src` attribute empty until the user hits the play button. AFAIK browsers will generally begin downloading any `src` in an `img` or `audio` tag at their own discretion.

**Comment by smbsimon** [comment]
@devTristan Totally! I'm just not finding where that happens, though. The audio src is happening within the audio_play class, and then audio_play class is connected to the canPlay variable, where all the meat happens with the addEventListener. I'm just getting very lost in the jumble.

**Comment by derekprior** [comment]
What part of the code is responsible for dropping down the "audio" HTML element? You'll want to update that so that instead of: `<audio src="...">` it does something like `<audio data-src="...">`. Then in your `$('a.audio_play').click` function, copy that value to the proper `src` attribute.

Here's a simplified example: http://codepen.io/anon/pen/epadVm

**Comment by smbsimon** [comment]
@derekprior This example is super helpful. Thank you!
